name: lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint markdown

    steps:
      - uses: actions/checkout@v3
      - name: Install prettier
        run: |
          yarn global add prettier
      - name: Check Markdown format
        run: |
          prettier --check "**/*.md"
